Final project proposal
ColumbiaOSS/project-proposals-f2020 pull request #48
Opened 2020-09-28 22:57 UTC by fprospato

Accidentally sent PR to the wrong repository for the 09/24/2020 assignment. Kept old project ideas in the project file to show thought process when doing the old assignment

2020-09-29 20:58 UTC, timkpaine requested changes

2020-09-29 20:58 UTC, timkpaine commented on flp2111.md
> +Project link: https://github.com/karimerobles/quick-questions/projects/1
just link to https://github.com/karimerobles/quick-questions

2020-09-29 20:59 UTC, timkpaine commented
I would unfork your project from this repo. https://github.com/karimerobles/quick-questions is forked from https://github.com/ColumbiaOSS/project-proposals-f2020, but should probably be created from scratch otherwise you'll have weird history and linkage

2020-10-02 01:04 UTC, fprospato commented
Sending a new pull request with updated project link @timkpaine

2020-10-02 01:04 UTC, closed without merging