updated proposal
ColumbiaOSS/project-proposals-f2020 pull request #69
Opened 2020-09-30 01:00 UTC by sm4954

2020-10-04 23:02 UTC, timkpaine requested changes

2020-10-04 23:02 UTC, timkpaine commented on sm4954.md
> +[Repository Link](https://github.com/shengtanmao/supersampling-library.git)
remove .git

2020-10-06 21:52 UTC, sm4954 commented on sm4954.md
> +[Repository Link](https://github.com/shengtanmao/supersampling-library.git)
I removed .git from the repository link

2020-10-06 21:53 UTC, sm4954 reviewed
removed .git from repository link

2020-10-07 02:37 UTC, merged